GET http://localhost:4001/matricula

####

GET http://localhost:4001/curso/4

####

POST http://localhost:4001/curso
Content-Type: application/json

{
        "id": 4,
        "nombre": "Matemáticas Discretas",
        "nivel": 2,
        "idDocente": 1,
        "idCarrera": 1
}

###

PUT http://localhost:4001/curso
Content-Type: application/json

{
        "id": 4,
        "nombre": "Matemáticas Discretas & Lógica",
        "nivel": 2,
        "idDocente": 1,
        "idCarrera": 1
}

####

DELETE http://localhost:4001/curso/3